---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: openfaas-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://openfaas.github.io/faas-netes/
  timeout: 5m

