apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tiddlywiki
  name: tiddlywiki
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiddlywiki
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tiddlywiki
    spec:
      containers:
      - env:
        - name: wiki_name
          value: vemcompy
        - name: wiki_port
          value: "8080"
        - name: wiki_username
          value: admin
        - name: wiki_password
          value: admin
        - name: gzip
          value: "yes"
        - name: debug-level
          value: none
        image: vemcompy/tiddlywiki:latest
        imagePullPolicy: Always
        name: tiddlywiki
        volumeMounts:
        - mountPath: /app/vemcompy
          name: volume
      volumes:
      - hostPath:
          path: /data
        name: volume
