---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      version: 1.15.0-r1
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: false
    crd:
     # crd.create: `true` if the crd resources should be created
     create: true
     # crd.keep: `true` if the sealed secret CRD should be kept when the chart is deleted
     keep: true
