dnsmasq:
  customDnsEntries:
    - address=/nas/192.168.15.250
    - address=/k3s/192.168.1.15

persistentVolumeClaim:
  enabled: true

serviceWeb:
  loadBalancerIP: 192.168.15.240
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 192.168.15.241
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
