---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: apps
spec:
  releaseName: pihole
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 1.8.22
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
      interval: 5m
  values:
        dnsmasq:
          customDnsEntries:
            - address=/nas.vemcompy.net/192.168.15.250
            - address=/k3s.vemcompy.net/192.168.1.15   
            - address=/camila.vemcompy.net/192.168.1.117
            - address=/notas.vemcompy.net/192.168.1.64
            - address=/w10.vemcompy.net/192.168.1.126
            - address=/w7.vemcompy.net/192.168.1.126
            - address=/xcp-node.vemcompy.net/192.168.1.102
            - address=/xcp.vemcompy.net/192.168.1.106
            - address=/burgundy.vemcompy.net/192.168.1.119
            - address=/rp.vemcompy.net/192.168.15.17
        persistentVolumeClaim:
          enabled: false
        serviceWeb:
          #loadBalancerIP: 192.168.1.240
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer
        serviceDns:
          #loadBalancerIP: 192.168.1.241
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer
