---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 1
    defaultSettings:
      defaultDataPath: /longhorn
      defaultReplicaCount: 1
      createDefaultDiskLabeledNodes: true
      storageMinimalAvailablePercentage: "10"
      #backupTarget: nfs://10.10.10.31:/mnt/tardisk/k3s
    service:
     ui:
       type: LoadBalancer
       nodePort: null
     manager:
       type: ClusterIP
       nodePort: ""     
    ingress:
      enabled: false
      host: longhor
      tlsSecret: longhorn-cert
      tls: false
      annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
        # cert-manager.io/cluster-issuer: letsencrypt-prod
        # nginx.ingress.kubernetes.io/auth-type: basic
        # nginx.ingress.kubernetes.io/auth-secret: nginx-basic-auth-winston
        # nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - mmkay'
