---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: botkube
  rollback:
    enable: true
  chart:
    repository: https://infracloudio.github.io/charts
    name: botkube
    version: v0.12.0
  values:
    image:
      repository: infracloudio/botkube
      tag: latest
    serviceMonitor:
      enabled: true
    config:
      settings:
        clustername: k3s
      resources:
        - name: v1/pods                # Name of the resources e.g pod, deployment, ingress, etc. (Resource name must be in singular form)
          namespaces:
            include:  
              - all
            ignore:                 # List of namespaces to be ignored (omitempty), used only with include: all
              - kube-system
          events:                   # List of lifecycle events you want to receive, e.g create, update, delete, error OR all
            - create
            - delete
        - name: v1/services
          namespaces:
            include:  
              - all
            ignore:
              - 
          events:
            - create
            - delete
            - error
        - name: apps/v1/deployments
          namespaces:
            include:  
              - all
            ignore:
              -
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
        - name: apps/v1/statefulsets
          namespaces:
            include:  
              - all
            ignore:
              -
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
        - name: networking.k8s.io/v1beta1/ingresses
          namespaces:
            include:  
              - all
            ignore:
              -
          events:
            - create
            - delete
            - error
        - name: v1/nodes
          namespaces:
            include:  
              - all
            ignore:
              -
          events:
            - create
            - delete
            - error
        - name: v1/namespaces
          namespaces:
            include:  
              - all
            ignore:
              -
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumes
          namespaces:
            include:  
              - all
            ignore:
              -
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumeclaims
          namespaces:
            include:  
              - all
            ignore:
              -
          events:
            - create
            - delete
            - error
        - name: v1/secrets
          namespaces:
            include:  
              - all
            ignore:
              -
          events:
            - create
            - delete
            - error
        - name: v1/configmaps
          namespaces:
            include:  
              - all
            ignore:
              -
          events:
            - delete
            - error
        - name: apps/v1/daemonsets
          namespaces:
            include:  
              - all
            ignore:
              -
          events:
            - create
            - delete
            - error
            - update
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
        - name: batch/v1/jobs
          namespaces:
            include:  
              - all
            ignore:
              - kube-system
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
              - status.conditions[*].type
        - name: rbac.authorization.k8s.io/v1/roles
          namespaces:
            include:  
              - all
            ignore:
              -
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/rolebindings
          namespaces:
            include:  
              - all
            ignore:
              -
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/clusterroles
          namespaces:
            include:
              - all
            ignore:
              - 
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/clusterrolebindings
          namespaces:
            include:  
              - all
            ignore:
              -
          events:
            - create
            - delete
            - error
  valueFileSecrets:
  - name: "botkube-helm-values"
